import unittest
import src.lexer.lexer as lexer

class TestLexerReadSpecialSymbols(unittest.TestCase):

    def test_read_equal_to(self):
        source_code = "int a = 5;"
        lex = lexer.Lexer(source_code)
        int_token = lex.read_identifier()
        self.assertEqual(int_token.type, lexer.TokenType.INT)
        self.assertEqual(int_token.value, "int")
        lex.skip_whitespace()
        a_token = lex.read_identifier()
        self.assertEqual(a_token.type, lexer.TokenType.IDENTIFIER)
        self.assertEqual(a_token.value, "a")
        lex.skip_whitespace()
        equal_token = lex.read_special_symbol()
        self.assertEqual(equal_token.type, lexer.TokenType.EQUAL)
        self.assertEqual(equal_token.value, "=")
        lex.skip_whitespace()
        number_token = lex.read_number()
        self.assertEqual(number_token.type, lexer.TokenType.INTEGER_LITERAL)
        self.assertEqual(number_token.value, "5")
        semicolon_token = lex.read_special_symbol()
        self.assertEqual(semicolon_token.type, lexer.TokenType.SEMICOLON)
        self.assertEqual(semicolon_token.value, ";")
        self.assertEqual(lex.collected_errors, [])

    def test_read_not_equal(self):
        source_code = "if (a != b) { return 0; }"
        lex = lexer.Lexer(source_code)
        if_token = lex.read_identifier()
        self.assertEqual(if_token.type, lexer.TokenType.IF)
        self.assertEqual(if_token.value, "if")
        lex.skip_whitespace()
        left_paren = lex.read_special_symbol()
        self.assertEqual(left_paren.type, lexer.TokenType.LEFT_PARAN)
        self.assertEqual(left_paren.value, "(")
        a_token = lex.read_identifier()
        self.assertEqual(a_token.type, lexer.TokenType.IDENTIFIER)
        self.assertEqual(a_token.value, "a")
        lex.skip_whitespace()
        not_equal_token = lex.read_special_symbol()
        self.assertEqual(not_equal_token.type, lexer.TokenType.NOT_EQUAL)
        self.assertEqual(not_equal_token.value, "!=")
        lex.skip_whitespace()
        b_token = lex.read_identifier()
        self.assertEqual(b_token.type, lexer.TokenType.IDENTIFIER)
        self.assertEqual(b_token.value, "b")
        right_paren = lex.read_special_symbol()
        self.assertEqual(right_paren.type, lexer.TokenType.RIGHT_PARAN)
        self.assertEqual(right_paren.value, ")")
        lex.skip_whitespace()
        left_brace = lex.read_special_symbol()
        self.assertEqual(left_brace.type, lexer.TokenType.LEFT_BRACE)
        self.assertEqual(left_brace.value, "{")
        lex.skip_whitespace()
        return_token = lex.read_identifier()
        self.assertEqual(return_token.type, lexer.TokenType.RETURN)
        self.assertEqual(return_token.value, "return")
        lex.skip_whitespace()
        number_token = lex.read_number()
        self.assertEqual(number_token.type, lexer.TokenType.INTEGER_LITERAL)
        self.assertEqual(number_token.value, "0")
        semicolon_token = lex.read_special_symbol()
        self.assertEqual(semicolon_token.type, lexer.TokenType.SEMICOLON)
        self.assertEqual(semicolon_token.value, ";")
        lex.skip_whitespace()
        right_brace = lex.read_special_symbol()
        self.assertEqual(right_brace.type, lexer.TokenType.RIGHT_BRACE)
        self.assertEqual(right_brace.value, "}")
        self.assertEqual(lex.collected_errors, [])

    def test_multicharacter_symbols(self):
        source_code = "a && b || c"
        lex = lexer.Lexer(source_code)
        a_token = lex.read_identifier()
        self.assertEqual(a_token.type, lexer.TokenType.IDENTIFIER)
        self.assertEqual(a_token.value, "a")
        lex.skip_whitespace()
        and_token = lex.read_special_symbol()
        self.assertEqual(and_token.type, lexer.TokenType.LOGICAL_AND)
        self.assertEqual(and_token.value, "&&")
        lex.skip_whitespace()
        b_token = lex.read_identifier()
        self.assertEqual(b_token.type, lexer.TokenType.IDENTIFIER)
        self.assertEqual(b_token.value, "b")
        lex.skip_whitespace()
        or_token = lex.read_special_symbol()
        self.assertEqual(or_token.type, lexer.TokenType.LOGICAL_OR)
        self.assertEqual(or_token.value, "||")
        lex.skip_whitespace()
        c_token = lex.read_identifier()
        self.assertEqual(c_token.type, lexer.TokenType.IDENTIFIER)
        self.assertEqual(c_token.value, "c")
        self.assertEqual(lex.collected_errors, [])